""" delete camp the subcategories

Revision ID: 1c45fecc4562
Revises: 0dd108355e1b
Create Date: 2022-09-16 17:01:07.561831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c45fecc4562'
down_revision = '0dd108355e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subcategories_id_category_fkey', 'subcategories', type_='foreignkey')
    op.drop_column('subcategories', 'id_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('id_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subcategories_id_category_fkey', 'subcategories', 'categories', ['id_category'], ['id'])
    # ### end Alembic commands ###
