"""actulizacion corracion de relacione de modulo de categories y subcategories

Revision ID: 2b2ee729cb30
Revises: 8e8409504de8
Create Date: 2022-09-18 17:11:36.140953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2ee729cb30'
down_revision = '8e8409504de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('id_category', sa.Integer(), nullable=True))
    op.drop_constraint('subcategories_id_sucategory_fkey', 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'categories', ['id_category'], ['id'])
    op.drop_column('subcategories', 'id_sucategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('id_sucategory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key('subcategories_id_sucategory_fkey', 'subcategories', 'categories', ['id_sucategory'], ['id'])
    op.drop_column('subcategories', 'id_category')
    # ### end Alembic commands ###
