"""add models

Revision ID: 5747fe68c67c
Revises: d4f9734a35bf
Create Date: 2022-10-25 22:47:54.456134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5747fe68c67c'
down_revision = 'd4f9734a35bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images_product', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('images_product', 'quantity')
    op.drop_column('images_product', 'price')
    op.add_column('products', sa.Column('type_material_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Float(precision=2), nullable=True))
    op.create_foreign_key(None, 'products', 'type_material', ['type_material_id'], ['id'])
    op.drop_column('products', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'type_material_id')
    op.add_column('images_product', sa.Column('price', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('images_product', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('images_product', 'status')
    op.drop_table('images_user')
    op.drop_table('type_material')
    # ### end Alembic commands ###
