"""actulizacion de modele category

Revision ID: 8e8409504de8
Revises: b1bfdef6999d
Create Date: 2022-09-18 16:25:26.556887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8409504de8'
down_revision = 'b1bfdef6999d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('id_sucategory', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subcategories', 'categories', ['id_sucategory'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_column('subcategories', 'id_sucategory')
    # ### end Alembic commands ###
