"""actualizacion

Revision ID: b1bfdef6999d
Revises: c61e134722d0
Create Date: 2022-09-17 19:09:59.280353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bfdef6999d'
down_revision = 'c61e134722d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_constraint('subcategories_id_category_fkey', 'subcategories', type_='foreignkey')
    op.drop_column('subcategories', 'id_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('id_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subcategories_id_category_fkey', 'subcategories', 'categories', ['id_category'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'subcategory_id')
    # ### end Alembic commands ###
