"""add campo dni al model user

Revision ID: b5fa9c4cb52a
Revises: 1c45fecc4562
Create Date: 2022-09-16 21:59:17.470761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fa9c4cb52a'
down_revision = '1c45fecc4562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dni', sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, 'users', ['dni'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'dni')
    # ### end Alembic commands ###
