""" delete  attribute id_category the modole product

Revision ID: c61e134722d0
Revises: b5fa9c4cb52a
Create Date: 2022-09-17 16:21:37.396579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61e134722d0'
down_revision = 'b5fa9c4cb52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_subcategory_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'subcategory_id')
    op.add_column('subcategories', sa.Column('id_category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subcategories', 'categories', ['id_category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_column('subcategories', 'id_category')
    op.add_column('products', sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_subcategory_id_fkey', 'products', 'subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###
